### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/jupyterlab-nvdashboard#170]
Currently use Jenkins for build packages, which will be discontinued by year end. Would need to port builds to GitHub Actions.

**Comment by jakirkham** [comment]
An example of the work entailed is in this PR: https://github.com/rapidsai/dask-cuda/pull/1062 (though would look at recent [`.github`]( https://github.com/rapidsai/dask-cuda/tree/f98963dcd4fdc9a5adaba94c0dfdee6991603b87/.github ) and [`ci`]( https://github.com/rapidsai/dask-cuda/tree/f98963dcd4fdc9a5adaba94c0dfdee6991603b87/ci ) directories for recent developments)

**Comment by ajschmidt8** [comment]
The CI for this repository will likely look different than the rest of RAPIDS since it doesn't follow our conventions.

In past discussions, Jacob said he would handle the conventions for this repository.

For what it's worth, the https://github.com/rapidsai/dependency-file-generator repository is using [semantic-release](https://github.com/semantic-release/semantic-release) pretty successfully.

**Comment by AjayThorve** [comment]
this is now implemented since #169.
